### ISSUE TITLE
Image generation error

### ISSUE THREAD

**Issue by tettusud** [n-gao/collage-generator#1]
Hi
 First of all thanks for this work. I am getting this error , any idea?
`
ValueError: Image RGB array must be uint8 or floating point; found int64
`
  And also its not actually taking height and width into consideration , I tried 1920X1080 , It either trims the pic or not takes all pic from the input folder.

**Comment by n-gao** [comment]
Hi,
At which line?

**Comment by tettusud** [comment]
`    mpimg.imsave(args.output, img)
`
But again as mentioned in the algorithm its not sticking to the dimensions of the canvas. I mean if there are fewer images (like 5) its cropping it.

**Comment by n-gao** [comment]
There is not always a perfect fit with every number of images, depending on your input resolutions and output resolution. You either need input more images or choose a different aspect ratio. In regards to the ValueError, I will fix this.
